name: buildfork
on:
  workflow dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      
      -name: Cache
       uses: actions/cache@v4.2.3
       with: 
         path: ~/.npm
         key: buildCache
      -run: npm ci
      -run: npm test -- --coverage
        env:
          CI: true

      -name: Upload Code Coverage
       uses: actions/upload-artifact@v4.3.1
       with:
         name: codecoverage
         path: coverage

      -name: Build
       run: npm run buld

      -name: Upload Build Files
       uses: actions/upload-artifact@v4.3.1
       with: 
         name: build
         path: build
      

    

          
